version: "3.9"

services:
  fastchat-controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastchat:latest
    ports:
      - "21001:21001"
    environment:
      - LOGDIR=${LOGDIR}  # Define the LOGDIR environment variable
    volumes:
      - /ssd/adamlin/FastChat/log:${LOGDIR}  # Mount the host directory to LOGDIR
    entrypoint: ["python3.9", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
  gradio-web-server:
    image: fastchat:latest  # Assuming the same image can be used
    depends_on:
      - fastchat-controller  # Ensure this service starts after the fastchat-controller
    ports:
      - "80:80"
    command: ["python3.9", "-m", "fastchat.serve.gradio_web_server_multi", "--show-terms-of-use", "--register-api-endpoint-file", "${LOGDIR}/models.json", "--host", "0.0.0.0", "--port", "80", "--controller-url", "http://fastchat-controller:21001"]
    environment:
      - LOGDIR=${LOGDIR}  # Define the LOGDIR environment variable
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - /ssd/adamlin/FastChat/log:${LOGDIR}  # Mount the host directory to LOGDIR
