version: "3.9"

services:
  fastchat-controller:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: fastchat:1.0.0
    network_mode: "host"
    ports:
      - "21001:21001"
    environment:
      - LOGDIR=${LOGDIR}  # Define the LOGDIR environment variable
    volumes:
      - /ssd/adamlin/FastChat/log:${LOGDIR}  # Mount the host directory to LOGDIR
    entrypoint: ["python3.9", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
  gradio-web-server:
    image: fastchat:1.0.0  # Assuming the same image can be used
    depends_on:
      - fastchat-controller  # Ensure this service starts after the fastchat-controller
    network_mode: "host"
    ports:
      - "80:80"
    command: ["python3.9", "-m", "fastchat.serve.gradio_web_server_multi", 
              "--show-terms-of-use", 
              "--register-api-endpoint-file", "${LOGDIR}/models.json", 
              "--host", "0.0.0.0", 
              "--port", "80", 
              "--controller-url", "http://localhost:21001",
              #"--controller-url", "http://fastchat-controller:21001",
              # "--elo-results-file", "/monitor/elo_results_20240130.pkl",
              # "--leaderboard-table-file", "/monitor/leaderboard_table_20240131.csv",
              ]
    environment:
      - LOGDIR=${LOGDIR}  # Define the LOGDIR environment variable
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - /ssd/adamlin/FastChat/log:${LOGDIR}  # Mount the host directory to LOGDIR
      - /ssd/adamlin/FastChat/fastchat/serve/monitor:/monitor  
  gradio-monitor:
    image: fastchat:1.0.0  # Assuming the same image can be used
    depends_on:
      - fastchat-controller  # Ensure this service starts after the fastchat-controller
    ports:
      - "8888:8888"
    network_mode: "host"
    command: ["python3.9", "-m", "fastchat.serve.monitor.monitor", "--host", "0.0.0.0", "--port", "8888"]
    environment:
      - LOGDIR=${LOGDIR}  # Define the LOGDIR environment variable
    volumes:
      - /ssd/adamlin/FastChat/log:${LOGDIR}  # Mount the host directory to LOGDIR
